export const doctors = [
  {
    id: 1,
    name: "Dr. John Smith",
    speciality: "Cardiologist",
    experience: 15,
    rating: 4.8,
    photo: "photos/dr_john_smith.png",
    reviews: [],
  },
  {
    id: 2,
    name: "Dr. Sarah Johnson",
    speciality: "Dermatologist",
    experience: 12,
    rating: 4.6,
    photo: "photos/dr_sarah_johnson.png",
    reviews: [],
  },
  {
    id: 3,
    name: "Dr. Michael Brown",
    speciality: "Orthopedic Surgeon",
    experience: 18,
    rating: 4.9,
    photo: "photos/dr_micahel_brown.png",
    reviews: [],
  },
  {
    id: 4,
    name: "Dr. Emily Davis",
    speciality: "Neurologist",
    experience: 14,
    rating: 4.7,
    photo: "https://via.placeholder.com/250x250?text=Dr.+Emily+Davis",
    reviews: [],
  },
  {
    id: 5,
    name: "Dr. Robert Wilson",
    speciality: "Gastroenterologist",
    experience: 16,
    rating: 4.5,
    photo: "https://via.placeholder.com/250x250?text=Dr.+Robert+Wilson",
    reviews: [],
  },
  {
    id: 6,
    name: "Dr. Lisa Martinez",
    speciality: "Pediatrician",
    experience: 11,
    rating: 4.8,
    photo: "https://via.placeholder.com/250x250?text=Dr.+Lisa+Martinez",
    reviews: [],
  },
  {
    id: 7,
    name: "Dr. James Anderson",
    speciality: "Pulmonologist",
    experience: 17,
    rating: 4.7,
    photo: "https://via.placeholder.com/250x250?text=Dr.+James+Anderson",
    reviews: [],
  },
  {
    id: 8,
    name: "Dr. Jennifer Garcia",
    speciality: "Endocrinologist",
    experience: 13,
    rating: 4.6,
    photo: "https://via.placeholder.com/250x250?text=Dr.+Jennifer+Garcia",
    reviews: [],
  }
];
